[package]
name = "penandink"
version = "0.1.0"
authors = ["Tobias Frilling <tobias@frilling-online.de>"]
edition = "2018"

[dependencies]
csv = "*"
rand = "*"
serde = { version = "*", features = ["derive"] }
